version: "3.9"

services:
  backend:
    build: .
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-g7&n*5lth6bcg)0ui*row++lezc3fzd^-s$)ler+##o!adrcpj
      - ALLOWED_HOSTS=*
      - MEDIA_ROOT=/app/media
      - STATIC_ROOT=/app/static
      - SERVER_IP=0.0.0.0
      - REDIS_HOST=redis
    volumes:
      - coolify_workspaces:/app/media/workspaces
      - coolify_static:/app/static
    command: >
      bash -c "python manage.py migrate && python manage.py collectstatic --noinput && exec daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  coolify_workspaces:
  coolify_static:
