version: "3.9"

services:
  # Django backend
  backend:
    build: .
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - coolify_workspaces:/app/media/workspaces
      - coolify_static:/app/static
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               exec daphne -b 0.0.0.0 -p 8000 sales_crm.asgi:application"
    depends_on:
      - redis
      - db

  # Redis service
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    env_file:
      - .env


volumes:
  coolify_workspaces:
  coolify_static:
  postgres_data:
