services:
  db:
    image: postgres:15  # Using Postgres 15
    container_name: sales_crm_db
    restart: always
    environment:
      POSTGRES_DB: builder        # Matches "NAME"
      POSTGRES_USER: ratish       # Matches "USER"
      POSTGRES_PASSWORD: "123"    # Matches "PASSWORD"
    ports:
      - "5433:5432"               # Maps host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sales_crm_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: